# Generated by Django 3.2.2 on 2021-05-12 17:43

import django.contrib.gis.db.models.fields
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(decoder=django.core.serializers.json.DjangoJSONEncoder, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.tracker')),
            ],
        ),
    ]
