# Generated by Django 3.2.2 on 2021-05-17 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The timestamp of this location'),
        ),
    ]
