# Generated by Django 3.2.2 on 2021-05-17 15:55

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='metadata',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
