# Generated by Django 3.2.2 on 2021-06-14 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210614_1806'),
        ('location', '0004_alter_location_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.tracker'),
        ),
    ]
