# Generated by Django 3.2.2 on 2021-05-12 17:43

import django.core.serializers.json
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(help_text='Human readable name for this tracker')),
                ('description', models.TextField(help_text='Description of this tracker')),
                ('metadata', models.JSONField(decoder=django.core.serializers.json.DjangoJSONEncoder, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Extra metadata about the tracker.')),
            ],
        ),
    ]
