# Generated by Django 3.2.2 on 2021-05-17 15:55

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='metadata',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Extra metadata about the tracker.'),
        ),
    ]
