# Generated by Django 3.2.2 on 2021-09-11 07:04

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210614_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Extra metadata about the tracker.'),
        ),
    ]
